### PR TITLE
Adding Validator (Syd - Mina FR Staking Community)

### PR DESCRIPTION
**Pull request by Syd-ai**

### CODE REVIEW

**Comment by wjdfx** [comment]
Can you resize your logo to 128*128px ?

**Comment by Syd-ai** [comment]
> Can you resize your logo to 128*128px ?

Oops sorry, yes, done

**Comment by wjdfx** [comment]
> > Can you resize your logo to 128*128px ?
> 
> Oops sorry, yes, done

still incorrect. now is 127*128px

**Comment by wjdfx** [comment]
and can you only change youself file.

**Pull request closed without merging**
